[project]
name = 'IP-Rights-Management-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.copyright-registration]
path = 'contracts/copyright-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.licensing-agreement]
path = 'contracts/licensing-agreement.clar'
clarity_version = 2
epoch = 2.5

[contracts.royalty-distribution]
path = 'contracts/royalty-distribution.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
